# Pandas CheatSheet

[Full documentation]().
- `DataFrame` - 2-dimensional labeled data structure with columns of potentially different types.
- `Series` - one-dimensional labeled array capable of holding any data type.

## Load CSV

In [1]:
import pandas as pd

df = pd.read_csv("data/Spotify-2000.csv") # returns DataFrame

# head(n) prints list of n items in DataFrame
df.head(5)

,Index,Title,Artist,Top Genre,Year,Beats Per Minute (BPM),Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76
4,5,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59

## Metadata

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 15 columns):
Index                     1994 non-null int64
Title                     1994 non-null object
Artist                    1994 non-null object
Top Genre                 1994 non-null object
Year                      1994 non-null int64
Beats Per Minute (BPM)    1994 non-null int64
Energy                    1994 non-null int64
Danceability              1994 non-null int64
Loudness (dB)             1994 non-null int64
Liveness                  1994 non-null int64
Valence                   1994 non-null int64
Length (Duration)         1994 non-null object
Acousticness              1994 non-null int64
Speechiness               1994 non-null int64
Popularity                1994 non-null int64
dtypes: int64(11), object(4)
memory usage: 233.8+ KB

In [3]:
df.columns

Index(['Index', 'Title', 'Artist', 'Top Genre', 'Year',
       'Beats Per Minute (BPM)', 'Energy', 'Danceability', 'Loudness (dB)',
       'Liveness', 'Valence', 'Length (Duration)', 'Acousticness',
       'Speechiness', 'Popularity'],
      dtype='object')

In [4]:
df.rename(columns={"Beats Per Minute (BPM)":"BPM"}, inplace=True) # rename column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Data columns (total 15 columns):
Index                1994 non-null int64
Title                1994 non-null object
Artist               1994 non-null object
Top Genre            1994 non-null object
Year                 1994 non-null int64
BPM                  1994 non-null int64
Energy               1994 non-null int64
Danceability         1994 non-null int64
Loudness (dB)        1994 non-null int64
Liveness             1994 non-null int64
Valence              1994 non-null int64
Length (Duration)    1994 non-null object
Acousticness         1994 non-null int64
Speechiness          1994 non-null int64
Popularity           1994 non-null int64
dtypes: int64(11), object(4)
memory usage: 233.8+ KB

## Reading data

In [5]:
df[["Title", "Artist"]].head(5) # Projection (select columns)

                    Title             Artist
0                 Sunrise        Norah Jones
1             Black Night        Deep Purple
2          Clint Eastwood           Gorillaz
3           The Pretender       Foo Fighters
4  Waitin' On A Sunny Day  Bruce Springsteen

In [6]:
df.iloc[1] # Selection by index

Index                          2
Title                Black Night
Artist               Deep Purple
Top Genre             album rock
Year                        2000
BPM                          135
Energy                        79
Danceability                  50
Loudness (dB)                -11
Liveness                      17
Valence                       81
Length (Duration)            207
Acousticness                  17
Speechiness                    7
Popularity                    39
Name: 1, dtype: object

In [7]:
df.iloc[0:4]

,Index,Title,Artist,Top Genre,Year,BPM,Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity
0,1,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71
1,2,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39
2,3,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69
3,4,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76

## Modifying data

In [8]:
df["Score"] = df["Energy"] + df["Danceability"] # Create new column
df.iloc[:, [0,1,2,15]].head(5)

   Index                   Title             Artist  Score
0      1                 Sunrise        Norah Jones     83
1      2             Black Night        Deep Purple    129
2      3          Clint Eastwood           Gorillaz    135
3      4           The Pretender       Foo Fighters    139
4      5  Waitin' On A Sunny Day  Bruce Springsteen    140

In [9]:
df.drop("Index", axis=1, inplace=True) # Remove column
df.head(5)

,Title,Artist,Top Genre,Year,BPM,Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity,Score
0,Sunrise,Norah Jones,adult standards,2004,157,30,53,-14,11,68,201,94,3,71,83
1,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39,129
2,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,66,-9,7,52,341,2,17,69,135
3,The Pretender,Foo Fighters,alternative metal,2007,173,96,43,-4,3,37,269,0,4,76,139
4,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59,140

In [10]:
# Set Danceability to 90 if BPM is higher then 150
df.loc[df[df.columns[4]] > 150, ["Danceability"]] = 90 
df.head(5)

,Title,Artist,Top Genre,Year,BPM,Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity,Score
0,Sunrise,Norah Jones,adult standards,2004,157,30,90,-14,11,68,201,94,3,71,83
1,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39,129
2,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,90,-9,7,52,341,2,17,69,135
3,The Pretender,Foo Fighters,alternative metal,2007,173,96,90,-4,3,37,269,0,4,76,139
4,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59,140

## Filtering

In [11]:
filtered = df.loc[(df["Energy"] > 60)].head(5) # Filter based on column value
filtered

,Title,Artist,Top Genre,Year,BPM,Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity,Score
1,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39,129
2,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,90,-9,7,52,341,2,17,69,135
3,The Pretender,Foo Fighters,alternative metal,2007,173,96,90,-4,3,37,269,0,4,76,139
4,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59,140
6,She Will Be Loved,Maroon 5,pop,2002,102,71,71,-6,13,54,257,6,3,74,142

In [12]:
filtered.reset_index(inplace=True, drop=True) # Resets index counter
filtered.head(5)

,Title,Artist,Top Genre,Year,BPM,Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity,Score
0,Black Night,Deep Purple,album rock,2000,135,79,50,-11,17,81,207,17,7,39,129
1,Clint Eastwood,Gorillaz,alternative hip hop,2001,168,69,90,-9,7,52,341,2,17,69,135
2,The Pretender,Foo Fighters,alternative metal,2007,173,96,90,-4,3,37,269,0,4,76,139
3,Waitin' On A Sunny Day,Bruce Springsteen,classic rock,2002,106,82,58,-5,10,87,256,1,3,59,140
4,She Will Be Loved,Maroon 5,pop,2002,102,71,71,-6,13,54,257,6,3,74,142

In [13]:
df.loc[df["Popularity"] > 70, ["Artist"]].head(10) # Filter & projection

               Artist
0         Norah Jones
3        Foo Fighters
6            Maroon 5
8         The Killers
9              Eminem
11  The White Stripes
19  Justin Timberlake
20           Coldplay
27             Eminem
30           Coldplay

## Sorting

In [14]:
df.sort_values(["Energy", "Artist"], ascending=[False, True]).head(5) # Sort by Energy - asc & Artist - desc

,Title,Artist,Top Genre,Year,BPM,Energy,Danceability,Loudness (dB),Liveness,Valence,Length (Duration),Acousticness,Speechiness,Popularity,Score
1345,Angel Of Death,Slayer,alternative metal,1986,90,100,28,-4,15,10,291,0,16,57,128
43,American Idiot,Green Day,modern rock,2004,186,99,90,-2,37,77,176,0,6,78,137
1395,Welcome To The Jungle,Guns N' Roses,glam metal,1987,124,99,45,-4,27,32,273,2,9,72,144
1278,When Doves Cry,Prince,funk,1984,126,99,73,-5,44,84,353,1,5,70,172
186,Go With The Flow,Queens of the Stone Age,alternative metal,2002,159,99,90,-4,83,37,187,1,10,58,123

## Aggregations

In [15]:
df.groupby(["Year", "Top Genre"]).mean().head(10) # Group by Year & Top Genre and produce mean values of all columns

                             BPM  Energy  Danceability  Loudness (dB)  \
Year Top Genre
1956 adult standards   95.000000    66.0     56.000000      -8.000000
1958 adult standards  144.600000    37.2     83.000000     -13.200000
1959 adult standards  133.000000    50.0     49.000000     -10.000000
     bebop            174.000000    26.0     90.000000     -13.000000
     blues rock       168.000000    80.0     90.000000      -9.000000
1960 adult standards   87.000000    35.0     27.000000      -9.000000
1961 adult standards  100.000000    29.0     40.000000     -14.000000
1962 adult standards  121.333333    39.0     64.666667     -10.666667
1963 adult standards   87.000000    26.5     43.000000     -14.000000
     album rock       143.000000    17.0     75.000000     -19.000000

                       Liveness    Valence  Acousticness  Speechiness  \
Year Top Genre
1956 adult standards  14.000000  96.000000          65.0          6.0
1958 adult standards  23.400000  62.400000          74.6          7.2
1959 adult standards  16.000000  83.000000          74.0          3.0
     bebop             7.000000  60.000000          54.0          4.0
     blues rock       31.000000  97.000000          74.0          7.0
1960 adult standards  33.000000  33.000000          55.0          3.0
1961 adult standards  11.000000  34.000000          94.0          3.0
1962 adult standards   6.666667  64.666667          58.0          4.0
1963 adult standards  12.000000  45.000000          79.5          4.0
     album rock       15.500000  45.500000          90.0          4.5

                      Popularity       Score
Year Top Genre
1956 adult standards   62.000000  122.000000
1958 adult standards   67.800000   89.800000
1959 adult standards   56.000000   99.000000
     bebop             65.000000   71.000000
     blues rock        74.000000  133.000000
1960 adult standards   74.000000   62.000000
1961 adult standards   78.000000   69.000000
1962 adult standards   75.666667  103.666667
1963 adult standards   58.000000   69.500000
     album rock        67.000000   66.000000

In [16]:
df["Year"].value_counts().sort_index().head(20)

1956     1
1958     5
1959     3
1960     1
1961     1
1962     3
1963     7
1964     9
1965    15
1966    20
1967    37
1968    27
1969    38
1970    40
1971    43
1972    29
1973    29
1974    23
1975    36
1976    31
Name: Year, dtype: int64

In [17]:
df.describe()

,Year,BPM,Energy,Danceability,Loudness (dB),Liveness,Valence,Acousticness,Speechiness,Popularity,Score
count,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.00000,1994.000000
mean,1992.992979,120.215647,59.679539,59.770812,-9.008526,19.012036,49.408726,28.858074,4.994985,59.52658,112.917753
std,16.116048,28.028096,22.154322,18.431036,3.647876,16.727378,24.858212,29.011986,4.401566,14.35160,28.660955
min,1956.000000,37.000000,3.000000,10.000000,-27.000000,2.000000,3.000000,0.000000,2.000000,11.00000,24.000000
25%,1979.000000,99.000000,42.000000,47.000000,-11.000000,9.000000,29.000000,3.000000,3.000000,49.25000,92.000000
50%,1993.000000,119.000000,61.000000,58.000000,-8.000000,12.000000,47.000000,18.000000,4.000000,62.00000,116.000000
75%,2007.000000,136.000000,78.000000,72.000000,-6.000000,23.000000,69.750000,50.000000,5.000000,71.00000,136.000000
max,2019.000000,206.000000,100.000000,96.000000,-2.000000,99.000000,99.000000,99.000000,55.000000,100.00000,183.000000